---
compliments:
  give_luck: true
  luck_amount: 0.05
  comp_scenes: true
  permissions:
    view_comps: View compliments on others. 
  achievements:
    gave_comps:
      type: comp
      message: Gave %{count} compliments.
